import sample_codes from "./sampleCodes.js"

const Sect_example = () => {
    
    return (
        <section id="examples" className="code-example">
            <h2 className="section-title">See it in Action</h2>
            <div className="example-container">
               <div className="output-block">
                    <h3>React JS - Navbar component </h3>
                    <p style={{paddingBottom: "10px"}}>Component styling: Navigation bar of this site: /src/components/nav/nav.jcss</p>
                    <div className="css-output">
                        <pre >
                            {sample_codes.navbar}
                        </pre>
                    </div>
                </div>
            </div>
            <div className="example-container">
               <div className="output-block">
                    <h3>React JS - main.jcss</h3>
                    <p style={{paddingBottom: "10px"}}>This is the main file where you write chaincss, javascript or even mixed with native css code</p>
                    <div className="css-output">
                        <pre >
                            {sample_codes.mainjcss}
                        </pre>
                    </div>
                </div>
            </div>
            <div className="example-container">
               <div className="output-block">
                    <h3>Generated CSS </h3>
                    <p style={{paddingBottom: "10px"}}>⚠️ Minified css auto generated by chaincss at /src/style/global.css you don't need to touch this part</p>
                    <div className="css-output">
                        <pre >
                            {sample_codes.generatedCSS}
                        </pre>
                    </div>
                </div>
            </div>
        </section>
    )
}

export default Sect_example